### PR TITLE
msglist: Add channel-feed action from topic narrows

### PR DESCRIPTION
**Pull request by gnprice**
Also apply our "icon" color to icon buttons more broadly.

Fixes: #1040

## Selected commit messages

theme: Apply icon color through IconButtonTheme

The most conspicuous change this makes is to the "back" icon
in an AppBar, aka AppBar.leading.  Those have been a white or
black color from Material defaults; now they get our "icon" color.

This matches what's in Figma; and also matches the action icons,
for any app bars that have both.  Currently our only app bar with
an action is also the only one that lacks a "leading": it's on
ChooseAccountPage, which is at the root of navigation so there's
nowhere for a "back" icon to lead to.  But when we add actions in
other pages, the mismatch would become conspicuous.

This change also turns a handful of less-visible icon buttons
from white/black to the icon color: the lightbox's "copy link"
or play/pause buttons, and the show/hide-password button on the
username/password login page.  I think those changes are desirable
too.  All our other icon buttons that I can find (either in the
source, or by browsing around the app) already have a color
specified, and aren't affected by this change.

---

msglist: Add channel-feed action from topic narrows

Fixes: #1040

### CODE REVIEW

**Comment by Dhanesh-Sawant** [comment]
Hi @gnprice,

Apologies for not addressing the requested changes sooner—I was tied up with exams. I completely agree with your feedback on commit style, testing, and other improvements.

Thank you for implementing the feature in PR #1072. I'll review it to learn and improve for future contributions.

**Comment by gnprice** [comment]
Cool. Hope your exams went well.

**Comment by gnprice** [comment]
(Oh, I should upload screenshots for the visual changes — I already went to the trouble of taking them. Short on time this morning but I'll try to do so later today.)

**Comment by chrisbobbe** [comment]
The code LGTM and so does the UI (including those changed icon colors); please merge at will, with or without posting those screenshots.

**Comment by gnprice** [comment]
Thanks for the review! For expediency and since the UI changes are all small, I'll just go ahead and merge, then.

**Pull request merged**
