### PR TITLE
Intl: Rename stream to channel in translation labels

### PR DESCRIPTION
**Pull request by Khader-1**
This is the first one of a series of PRs that target #631.

Fixes parts of #631

### CODE REVIEW

**Review by rajveermalviya — APPROVED** [review]
Thanks @Khader-1, LGTM :)

Over to @kenclary for mentor review.

**Review by kenclary — APPROVED** [review]
lgtm

**Comment by chrisbobbe** [comment]
Thanks! LGTM except let's squash the second commit into the first, so that we don't have a commit where there's a reference that uses the wrong (outdated) name of something.

Marking for Greg's review.

**Comment by gnprice** [comment]
Thanks all! This LGTM except the point Chris mentioned above, and one nit:

041479d0e intl: Rename string labels `stream` to `channel`

The commit-summary prefix we've mainly used for this area is `i18n:`.

I'll fix both of those and merge.

**Pull request merged**
