### PR TITLE
internal_link: Generate narrow links with "channel", not "stream"

### PR DESCRIPTION
**Pull request by sm-sayedi**
Fixes: #633

### CODE REVIEW

**Review by Khader-1 — APPROVED** [review]
Thanks! LGTM.
Let's move on to the mentor review with @hackerkid

**Comment by chrisbobbe** [comment]
Thanks @sm-sayedi! This needs a feature-level condition, as mentioned in #633 and the zulip-mobile issue linked from there.

**Comment by sm-sayedi** [comment]
> This needs a feature-level condition, as mentioned in #633 and the zulip-mobile issue linked from there.

Does it mean we should wait for some time or a condition should be used in the code?

**Comment by gnprice** [comment]
> Does it mean we should wait for some time or a condition should be used in the code?

Both :slightly_smiling_face: It'll need a feature-level condition so we generate these only when the server is new enough that its web app understands these links; and we'll also want to wait for some time, so that mobile users who don't get prompt updates (the majority do, but many don't) reach a version that understands these links.

That wait just became clearer a few days ago, after [an `#api design` thread](https://chat.zulip.org/#narrow/stream/378-api-design/topic/URLs.20for.20stream.20to.20channel.20rename/near/1846142) prompted by the question of when to start generating these on web. I've updated #633 accordingly, and pushed it to a later milestone.

Because it'll be a few months before we can deploy an implementation of this, let's pause work on it for now, and I'll close this PR. The PR will remain linked from the issue, so we can always draw on it when we do pick up the issue in the future.

**Pull request closed without merging**
