### PR TITLE
notif: Switch to our own Pigeon-based plugin for showing a notification

### PR DESCRIPTION
**Pull request by gnprice**
This delivers the first major tranche of #351, switching from
package:flutter_local_notifications to our own thin API binding
based on Pigeon. In particular we convert over one of
the handful of different methods we use from that package,
and it's the most complex of them by a substantial margin.

Getting this to work involves a bit of tricky, but fortunately
one-time, infrastructure: a shim extra Flutter plugin in order
to get our new Flutter plugin properly wired up.

Fixes-partly: #351

/cc @rajveermalviya

### CODE REVIEW

**Comment by chrisbobbe** [comment]
```
FAILED: analyze build_runner
```

**Comment by gnprice** [comment]
Ah thanks.

The analyze failure is this issue I reported upstream in Pigeon:
* https://github.com/flutter/flutter/issues/145633

but that I then forgot about when sending this. I'll work around probably by just disabling the lint globally; I doubt many cases of it will accumulate before someone (possibly us) gets around to fixing that Pigeon issue.

The build_runner failure looks like I need to tweak that check to know that not all `*.g.dart` files come from build_runner.

I'll fix those, but meanwhile I think all the existing code in the PR is ready for review.

**Comment by gnprice** [comment]
Fixed those issues — CI is now passing.

**Comment by chrisbobbe** [comment]
Cool! It's exciting to start using Pigeon.

In manual testing on the office Android device (Samsung Galaxy S9 running Android 9), I don't seem to be getting notifications when the app is closed. They do appear when the app is open and foregrounded, or open in the background.

I'm not sure if this behavior is new with these commits, though. I'll check and see what's happening on `main`.

**Comment by chrisbobbe** [comment]
Ah yeah, I see the same thing happening on `main`. So I guess there's an existing bug. Is it possible this is related to #342?

**Comment by gnprice** [comment]
Yeah, I actually saw similar behavior when I was testing this yesterday, and similarly determined it was also present on main :-/ I have a local note to myself but hadn't gotten to investigating further.

It's probably yet another distinct cause from #342, but definitely a similar symptom.

One potential mitigating factor is that I think I've only seen that in debug builds, not when using `flutter run --release`. If that pattern holds, then it doesn't affect normal users. But I don't know of a good reason why it'd have that pattern.

**Comment by chrisbobbe** [comment]
Oh, FWIW the issue seems to have stopped reproducing for me. I'm still on `main`. Here is my sequence:

- Freshly install a debug build from `main`, open the app, log in
- Cause a notification via DM; it appears (reported above)
- Put the app in the background
- Cause a notification via DM; it appears (reported above)
- Close the app
- Cause a notification via DM; it does not appear (reported above)
- Open the app again
- Cause a notification via DM; it appears
- Put the app in the background
- Cause a notification via DM; it appears
- Close the app
- Cause a notification via DM; it appears! (unexpected)

Did you happen to notice something similar?

**Comment by chrisbobbe** [comment]
Anyway, the issue is present in `main` so shouldn't block merging this. Please merge at will. 🙂

**Comment by gnprice** [comment]
> Oh, FWIW the issue seems to have stopped reproducing for me. I'm still on `main`.

Yeah, the issue has been flaky in my observation — sometimes it reproduces, sometimes not. That's the main reason I'm not confident in the "only debug builds" pattern I've observed.


> Here is my sequence:
> 
> * Freshly install a debug build from `main`, open the app, log in
> * Cause a notification via DM; it appears (reported above)
> * Put the app in the background
> * Cause a notification via DM; it appears (reported above)
> * Close the app
> * Cause a notification via DM; it does not appear (reported above)

Yeah, this is exactly the sequence that I did many times in the course of developing these changes (repeating it after various changes to the branch, to check that things were still working).

I suspect a trigger for it might be that closing the app is taken as a bad sign by the system — the user force-closed the app! maybe it was misbehaving for them — and so because I was doing it again and again, the system eventually decided the app shouldn't be trusted with the privilege of starting up in the background. If so, then that'd be another mitigating factor in that it's not likely to happen with users who aren't developing the app.

**Comment by gnprice** [comment]
Merged! Thanks for the review.

**Comment by gnprice** [comment]
And filed #597 for that issue where notifications sometimes don't appear.

**Pull request merged**
