### PR TITLE
41 show user avatar

### PR DESCRIPTION
**Pull request by aanelson**
Got basic avatar functionality.  Also checked in something to disable auto formatting with vscode.  It still occasionally doesn't work and formats the whole file.

Was writing test to verify the close behavior, but was blocked by https://github.com/zulip/zulip-flutter/issues/30.

Used ClipOval instead of CircleAvatar as that takes an ImageProvider instead of a widget and there is currently nothing setup to generate it with the headers.

### CODE REVIEW

**Review by gnprice — COMMENTED** [review]
Thanks @aanelson! Looking forward to getting this in. A few comments below.

One overall comment that applies to several spots below is that in the Zulip project, we make a practice of keeping a clean commit history: each Git commit does a single thing and does it in a self-contained way. More discussion here:
https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html

So in particular that means that
* we'll want the edits to the `avatar` computation and the `actions` property in the latter two commits to get squashed into the same commit that makes the other main changes;
* we'll want other, unrelated, changes to get separated out into their own commits.

Relatedly, we have a [preferred style for commit messages](https://zulip.readthedocs.io/en/latest/contributing/commit-discipline.html#commit-messages) that helps us scan the history for release management and debugging. For examples, see `git log` in the repo.

**Comment by gnprice** [comment]
> Was writing test to verify the close behavior, but was blocked by #30.

Mmm, yeah, that makes sense. This is a good reminder that we should go ahead and take care of that; I've just bumped it up our priority list.

**Comment by aanelson** [comment]
@gnprice Updated.  I don't know of a way to keep the comments in the correct location when updating the commits so that will be broke, but I have addressed the issues.

**Review by gnprice — COMMENTED** [review]
Thanks @aanelson for the revision!  I appreciate the cleanly separated commits.

Comments below on the code, and some observations from playing with this version on a device.

**Pull request closed without merging**
