### PR TITLE
msglist: Cut excess spacing between sender and paragraph

### PR DESCRIPTION
**Pull request by chrisbobbe**
This is the "easy hack" Greg mentions in the description of #513.

Fixes: #513

### CODE REVIEW

**Comment by chrisbobbe** [comment]
| Before | After |
| --- | --- |
| image | image |

**Comment by chrisbobbe** [comment]
(I didn't mark this with `Fixes:` because it doesn't do the "fixing this properly" thing that you described in the issue.)

**Comment by gnprice** [comment]
Thanks!

I think this can actually be best described as fixing #513. This does fix the excess spacing, just in a way that potentially goes too far for certain content. And the work that it leaves open is basically part of #162.

**Comment by gnprice** [comment]
Looks good; merging, after that metadata tweak.

**Comment by chrisbobbe** [comment]
Cool, thanks!

**Pull request merged**
