### PR TITLE
content: Use 17 for base font size, and fix code/mentions/times in headings

### PR DESCRIPTION
**Pull request by chrisbobbe**
| Before | After |
| --- | --- |
| image | image | 
| image | image |
| image | image |
| image | image |

Fixes: #512
Fixes: #538

### CODE REVIEW

**Comment by gnprice** [comment]
Thanks for cleaning these up! The code changes all look good to me. A couple of tests are failing, though.

**Comment by chrisbobbe** [comment]
Those tests are helpful indeed! Hmm. So the problem is that we're trying to apply the 0.825 `fontSize` multiplier for inline code in places that don't actually have a `fontSize` value to apply the multiplier to, e.g. (by the end of the branch), 17 for paragraphs and 23.8 for h1 headings. That will happen when the paragraph/h1/etc. isn't the thing directly surrounding the code span, such as when there's a strong (bold) or emphasis (italic) span around the code span.

For example, this content fails to render:

[hello ***`world`***](https://chat.zulip.org/)

In a CZO message: https://chat.zulip.org/#narrow/stream/7-test-here/topic/Chris/near/1748844

The error is:

```
The following assertion was thrown building InlineContent(dirty, dependencies: [MediaQuery]):
'package:flutter/src/painting/text_style.dart': Failed assertion: line 990 pos 12: 'fontSize != null || (fontSizeFactor == 1.0 && fontSizeDelta == 0.0)': is not true.
```

The code span is expecting to find a font size on the `TextStyle` of the surrounding span. That span is an emphasis (italic) span with just `const TextStyle(fontStyle: FontStyle.italic))`, so no `fontSize`.

**Comment by chrisbobbe** [comment]
To fix, we could maybe:

- For every span that might sit between a code span and a paragraph/h1/etc., make sure the span merges into its own style the font size of the span that surrounds it. This seems error-prone.
- In paragraphs/h1s/etc., use a `DefaultTextStyle` that provides the appropriate font size, and then the code-span code can consume it using `DefaultTextStyle.of`.

**Comment by gnprice** [comment]
I like the second direction, and I think we can simplify it: `DefaultTextStyle` is a way of specifying a style as an inherited widget, to be found from throughout that widget's subtree. But paragraphs and headings etc. are leaves in the widget tree — the further recursion that happens in the ContentNode tree is all producing spans for the one widget, not additional descendant widgets.

So instead of `DefaultTextStyle`, I think we can pass a style to _InlineContentBuilder as the default style, and then the code-span code can consume that and do the same thing it would do with the result of `DefaultTextStyle.of`.

**Comment by chrisbobbe** [comment]
Interesting; thank you!

**Comment by chrisbobbe** [comment]
> So instead of `DefaultTextStyle`, I think we can pass a style to _InlineContentBuilder as the default style

Doesn't `_InlineContentBuilder` already have this, kind of, and call it `widget.style`? (Except that `InlineContent.style` is optional, but could easily be made required?)

**Comment by gnprice** [comment]
Yeah, that seems right. So then that approach comes down to taking `widget.style` and drawing from it in more places, in the same way you might have done from `DefaultTextStyle.of`.

**Comment by chrisbobbe** [comment]
Since #541, we're now using 17 for the base font size.

I plan to close this and open a new PR for aimed at #538, with fresh screenshots (that will show the font-size 17 in the "before" column).

**Pull request closed without merging**
