### PR TITLE
Add a run-all-tests script, for local and CI use

### LINKED ISSUE #60: Set up CI: test, analyze, and generate
We should run our tests and other checks in a CI setup.

These consist of:
* `flutter test`
* `flutter analyze`
* Regenerating all generated files, and checking that nothing changed. This means:
  * The `build_runner` command mentioned in the README (but can use `build` instead of `watch`).
  * After #13, a couple of `drift_dev` commands that need to be run whenever the database schema changes; they'll be described in a comment at the spot where we define the current schema version.

(If we complete this before #13, that's fine; we'll leave out that last item, and just add it as part of #13.)

Some things that we'd ideally have but are optional for this issue (and we'll just file followup issues if they're not in the first implementation of this one):
* A handy wrapper script for local development use, like `tools/test` in zulip-mobile, that makes all the same checks we do in CI.
* That wrapper script being (again like `tools/test` in zulip-mobile) efficient about not redoing checks for things that shouldn't be affected by the local changes.
* That wrapper script being written in Dart, rather than Bash.

### PR DESCRIPTION
**Pull request by gnprice**
Fixes #60.

This introduces a script `tools/check` to run all our forms of tests.

Much like the `tools/test` in zulip-mobile, its CLI is optimized by default for local development; so you can type just `tools/check` at your command line, and it'll do its best to run just the relevant tests and emit helpful, low-noise output. See `tools/check --help` for further options.

And then this also adds a GitHub Actions workflow to run our tests for CI. After setup, the core of this is `tools/check --all --verbose`.

There's in fact one spot where we had a generated file that was out of sync with its source! The new test script catches that, and it'll help us avoid any similar discrepancy in the future. The first commit of this branch fixes the existing issue.

### CODE REVIEW

**Comment by gnprice** [comment]
Hmm, GitHub doesn't seem to be picking up the workflow here to run it.

Puzzling because it works fine on my fork gnprice/zulip-flutter:
https://github.com/gnprice/zulip-flutter/actions/runs/6388026962/job/17337209864
and I found I didn't have to configure anything to make that so; it just worked once I pushed a commit, to some branch, that had a workflow file in it. And because the repo settings on this repo seem to permit actions just fine.

I'll poke around the GitHub settings some more. But in any event, the code should all be ready for review.

**Comment by sirpengi** [comment]
> Hmm, GitHub doesn't seem to be picking up the workflow here to run it.
> 
> Puzzling because it works fine on my fork gnprice/zulip-flutter: https://github.com/gnprice/zulip-flutter/actions/runs/6388026962/job/17337209864 and I found I didn't have to configure anything to make that so; it just worked once I pushed a commit, to some branch, that had a workflow file in it. And because the repo settings on this repo seem to permit actions just fine.
> 
> I'll poke around the GitHub settings some more. But in any event, the code should all be ready for review.

I believe it's caused by this being a public repo: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories

**Comment by gnprice** [comment]
Chat thread for debugging: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/GitHub.20settings.20for.20CI/near/1653618

**Comment by gnprice** [comment]
Well, it's run now :shrug:, and passed. What I did was to push the PR branch to a temporary ad hoc branch within this repo (`tmp-test-ci`).

I think I've done enough investigation of GitHub's behavior for now. Given that it works when pushing to a branch here, this should definitely be enough that we get CI post-merge, i.e. upon pushing to `main`, which is a start. I'm hoping that once the workflow is merged, that will also cause it to start running on PRs; if it doesn't, we can do further investigation then.

**Comment by chrisbobbe** [comment]
Here's output I get from `tools/check --all` (after accepting and committing some [`pubspec.lock` changes](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/flutter.3A.20flutter_gen.20not.20found.3F/near/1655625) that were automatically made, I think when I ran `flutter run`):

```
$ tools/check --all
Running analyze...
Analyzing zulip-flutter...                                              
No issues found! (ran in 3.0s)
Running test...
00:21 +424 ~1: All tests passed!                                                   
Running build_runner...
[WARNING] json_serializable on test/test_clipboard.dart:
Your current `analyzer` version may not fully support your current SDK version.

Analyzer language version: 3.1.0
SDK language version: 3.2.0

Please update to the latest `analyzer` version (6.2.0) by running
`flutter packages upgrade`.

If you are not getting the latest version by running the above command, you
can try adding a constraint like the following to your pubspec to start
diagnosing why you can't get the latest version:

dev_dependencies:
  analyzer: ^6.2.0

[WARNING] No actions completed for 15.0s, waiting on:
  - json_serializable on test/test_clipboard.dart
  - json_serializable on test/test_navigation.dart
  - json_serializable on test/flutter_checks.dart
  - json_serializable on test/example_data.dart
  - json_serializable on test/stdlib_checks.dart
  .. and 11 more

Running drift...
Building package executable... (7.3s)
Built drift_dev:drift_dev.
Wrote to test/model/schemas/drift_schema_v2.json
Wrote 3 files into test/model/schemas
Running icons...

added 162 packages in 39s
Running shellcheck...
Passed!
```

What's `json_serializable` trying to do in the `test/` directory? Does it need to be doing anything there?

**Comment by chrisbobbe** [comment]
Otherwise LGTM! We can always fine-tune things later. One thing I can envision wanting in my routine workflow is that it doesn't waste time setting up and running tests if some bug makes that a pointless exercise and that bug was already flagged by the analyzer.

**Comment by gnprice** [comment]
Thanks for the review!


> What's `json_serializable` trying to do in the `test/` directory? Does it need to be doing anything there?

Hmm interesting. Yeah, we don't have anything for it to do there — but I suppose it needs to scan those files to find out that that's the case.

I'd expect that that scanning is fast, and that whatever took it 15+ seconds there was some kind of startup work that would have been the same regardless of which files were in the queue. In particular, that warning about the `analyzer` version would presumably apply the same on any file, so presumably the file it got reported at was the file that the tool happened to look at first — which means that `test/test_clipboard.dart` was the first file it looked at.



> Also I wonder about addressing that warning about "Your current `analyzer` version may not fully support your current SDK version", if only primarily to make `tools/check` give less output that might be distracting.

Yeah, definitely. I'd noticed that occasionally before, but it is a bit more annoying now in the context of this `tools/check` script.



> One thing I can envision wanting in my routine workflow is that it doesn't waste time setting up and running our unit tests if some bug makes that a pointless exercise and that bug was already flagged by the analyzer. Probably a fine approximation would be to just not run the `test` suite unless the `analyze` suite passed.

That's a bit tricky because the `analyze` suite could find some info-level issues — like "don't use `print`", which can be perfectly normal during development — or even warnings, but no errors. Then the VM will cheerfully run the code, and there may be no reason the tests wouldn't pass.

This is the reason why it runs `analyze` first, though — and similarly why in zulip-mobile `tools/test` runs the `flow` suite before `jest`. If it fails and that already tells you that you don't need to learn more, you can hit Ctrl+C to stop the tests and move on.

**Comment by chrisbobbe** [comment]
> If it fails and that already tells you that you don't need to learn more, you can hit Ctrl+C to stop the tests and move on.

Makes sense; ISTR doing that frequently when working in zulip-mobile.

**Pull request merged**
