### PR TITLE
Parameterize the ApiConnection in getServerSettings.

### PR DESCRIPTION
**Pull request by samwightt**
Parameterizes the ApiConnection in getServerSettings so that it can now be tested. Also fixes issue with `SlottedContainerRenderObjectMixin`, as it now requires two type parameters on Flutter `main`.

### CODE REVIEW

**Comment by gnprice** [comment]
> The first commit, making an API update for a change in Flutter main, looks good. I'll merge it shortly with small stylistic tweaks.

Done:
2f0f4692f sticky_header: Pass new second type argument to SlottedContainerRenderObjectMixin et al.

**Comment by gnprice** [comment]
I've rebased this PR branch on top of the now-merged version of your first commit, just because there'd otherwise be a small merge conflict for you to resolve.

**Comment by samwightt** [comment]
@gnprice Thanks for the feedback! Sorry, didn't realize there were so many formatting problems 😅  I'll take a look at this tomorrow and rebase + fix things :)

**Comment by samwightt** [comment]
@gnprice Agh sorry I'm not! Sorry about getting back to this so late.

**Comment by gnprice** [comment]
No worries! Thanks for the update.

**Pull request closed without merging**
