### PR TITLE
Navigate to conversation on tapping notification

### PR DESCRIPTION
**Pull request by gnprice**
Still only on Android; iOS support for notifications in general is coming next.

Fixes: #123

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Oh hmm, one thing I just noticed: is this meant to work when the app is not open at all, where tapping a notification is meant to cause a cold start of the app?

**Comment by gnprice** [comment]
> is this meant to work when the app is not open at all, i.e., where tapping a notification is meant to cause a cold start of the app? When I tap a notification when the app is completely closed, it does open the app, but just to the "Choose account" screen.

Hmmm good catch.

I think that is an important case for #123 — probably the most common case. I'll take a look at handling it.

**Comment by gnprice** [comment]
Thanks for the review! Updated — PTAL.

I acted on the small comment above and then also added three commits at the end to handle the launch-from-notification case.

**Comment by gnprice** [comment]
(As discussed at #352, on my device I still don't actually *get* notifications while the app is completely stopped. So wherever those symptoms apply, this still won't deliver a large swath of the value of getting a notification and opening it. That issue is tracked at #342.

But I can still manually test the issue you raised: open the app, cause a notification, *then* kill the app, then open the notification. The app was running when the notification appeared, but not when it was opened, so the opening of the notification is what launches the app.)

**Comment by chrisbobbe** [comment]
Thanks! Merged.

FWIW in my testing just now, on the office Android device, I also saw long delays in a notification appearing if the app was completely closed when the message was sent. The notifications did eventually arrive, but not before I opened the app again. (In fact, they didn't even arrive at the time I reopened the app—it took a surprisingly long time after that, maybe over a minute.)

So I managed to test the launch-from-notification case this way too:

> But I can still manually test the issue you raised: open the app, cause a notification, then kill the app, then open the notification. The app was running when the notification appeared, but not when it was opened, so the opening of the notification is what launches the app.

**Pull request merged**
