### PR TITLE
ui: Add animation support for the edited/moved marker.

### PR DESCRIPTION
**Pull request by PIG208**
This is a sequel to #762 that animates the swipe gesture.

### CODE REVIEW

**Comment by PIG208** [comment]
https://github.com/zulip/zulip-flutter/assets/39874143/ba3573bc-7932-498f-88cf-56e68812c9d1

**Comment by PIG208** [comment]
Incorporating @chrisbobbe 's [comment](https://github.com/zulip/zulip-flutter/pull/762#discussion_r1667193221), we animate the marker from the start state to the end state as follows:
| | margin left | margin right | paddings (horizontal symmetric) | distance between marker text and icon |
| - | - | - | - | - |
| Start | 5px | 3px | 0px | 0px |
| End | 13px | 3px | 3px | 5px |

where the paddings are the distances "between the left edge of the rounded-rectangle and 'Edited'" and "between the icon and the right edge of the rounded-rectangle", the margins are the distance between the rectangle to the left of the screen and to the message content, respectively.

**Comment by PIG208** [comment]
Rebased since #762 has been merged. We will need to get back to this later to investigate alternatives to `LayoutBuilder`.

**Comment by chrisbobbe** [comment]
My review is next, I think, right? I've just added "maintainer review" so I don't lose track of it.

**Comment by PIG208** [comment]
Yeah, this is not ready for review yet, but I will let you know once it is.

**Comment by gnprice** [comment]
Marked as draft because that makes it easier to remember (particularly when looking at a list of PRs) which PRs have become ready for review :slightly_smiling_face:

**Pull request closed without merging**
