### PR TITLE
deps: Flutter, packages, and fix macos/Podfile.lock

### PR DESCRIPTION
**Pull request by gnprice**
deps: Run `pod update sqlite3` in macos/

This is necessary for `flutter run` to work on a macOS target,
presumably since 5dbf1e635.

Similar to c5c094991 and 105727e15 for a previous upgrade.
The symptoms were just like those described in the latter commit.

---

deps: Upgrade Flutter to latest main, 3.16.0-11.0.pre.88

And update Flutter's supporting libraries to match.

---

deps: Upgrade packages within constraints (flutter pub upgrade)

Plus `flutter build ios --config-only`
and `flutter build macos --config-only`.

---

deps: Upgrade packages to latest, namely file_picker

This is the result of `flutter pub upgrade --major-versions`,
followed by `flutter build ios --config-only`.
(Plus `flutter build macos --config-only`, but it has no
effect, as file_picker doesn't appear in macos/Podfile.lock .)

Changelog:
  https://pub.dev/packages/file_picker/changelog

The API changes don't affect our usage.

### CODE REVIEW

**Comment by gnprice** [comment]
Added one more commit at the start:

    deps: Update CocoaPods to 1.13.0
    
    This is needed on Xcode 15, at least once certain packages are
    pulled in.  (In particular, firebase_core, which I have in a
    draft branch for handling notifications.)
    
    Upstream issue thread:
      https://github.com/CocoaPods/CocoaPods/pull/12009

**Comment by chrisbobbe** [comment]
> deps: Run `pod update sqlite3` in macos/

Ah hmm, yeah; I think I remember doing this in ios/ but I don't remember doing it in macos/. I wonder how easy it would be to add checks for this in CI.

**Comment by chrisbobbe** [comment]
Thanks, LGTM! Merged.

**Comment by gnprice** [comment]
> I wonder how easy it would be to add checks for this in CI.

Yeah. GitHub does offer macOS-based runners for actions:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

There's a steep 10x multiplier in how they count against our quota of free usage (and a similar steeper rate if paying for more):
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers
so we'll want to stick to Linux for all the suites where we can, but that shouldn't stop us from using macOS where necessary.

I'll file an issue.

**Pull request merged**
