### PR TITLE
feat: Added about zulip option to main menu

### PR DESCRIPTION
**Pull request by tomlin7**
fix: #1128 

## Changes
- Added **About Zulip** option to main menu

### CODE REVIEW

**Comment by chrisbobbe** [comment]
This will need to follow our Git style before it gets a review from a core team member. It also needs tests and localization.

**Comment by tomlin7** [comment]
@chrisbobbe I have added localization and tests for the "about zulip" menu button. Please let me know of the changes to be made for this to qualify as an appropriate commit.

**Comment by tomlin7** [comment]
@chrisbobbe noticed the commit messages, to not make any further mess here I will open a fresh new PR for this.

**Comment by chrisbobbe** [comment]
Please don't open a fresh new PR for the same work; that's not necessary. Just force-push to the same branch: https://zulip.readthedocs.io/en/latest/git/using.html

**Comment by tomlin7** [comment]
@chrisbobbe sure, I will keep that in mind. But #1146 has already been opened for this; please check.

**Comment by chrisbobbe** [comment]
> But #1146 has already been opened for this

I think you mean #1157? (This issue is #1146.)

**Comment by tomlin7** [comment]
@chrisbobbe my bad! pardon, I was a bit nervous about git rebase, and yes that is the correct PR #1157.

I have found this page really helpful: https://zulip.readthedocs.io/en/latest/git/fixing-commits.html

**Pull request closed without merging**
